### ISSUE TITLE
motion includes brackets

### ISSUE THREAD

**Issue by mightyCelu** [bkad/CamelCaseMotion#32]
When using `d,w` on `some_function(some, parameters)` while the cursor is at the `f`, the result is `somesome, parameters)`, i.e. the word includes the opening bracket. 

This is at least not the behavior I expect, so it might be unintended.

**Comment by bkad** [comment]
Hmm, I wasn't able to reproduce this problem. What's the file type you're working with? What do you get back when you type in ":set iskeyword?"

**Comment by mightyCelu** [comment]
For example this file:
```
def some_function(): 
    pass
```
When I use `d,w` on the f, it deletes everything until pass. `:set is_keyword` returns `iskeyword=@,48-57,_,192-255`

**Comment by spktklr** [comment]
+1

`iskeyword=@,48-57,_,192-255,#`

**Comment by scottgrayson** [comment]
Same problem for me.
Example:
```
public function [i]ndex(Request $request)
```
typing w makes cursor move to
```
public function index([R]equest $request)
```
expected behavior
```
public function index[(]Request $request)
```

Filetype is php. :set iskeyword returns iskeyword=@,48-57,_,192-255

**Comment by deepsweet** [comment]
same here, same `iskeyword` value

**Comment by kylemacfarlane** [comment]
Same problem here. I was using inkarkat's original version for years and the bug doesn't exist there so I compared the old search to the new one.

The current version:

    call search( '\m\<\D\|^$\|\%(^\|\s\)\+\zs\k\@!\S\|\>\<\|\d\+\|\l\+\zs\%(\u\|\d\)\|\u\+\zs\%(\u\l\|\d\)\|\u\l\+\|\u\@<!\u\+\|[-_]\zs\%(\u\+\|\u\l\+\|\l\+\|\d\+\)', 'W' . l:direction)

The old version:

    call search( '\<\D\|^$\|\%(^\|\s\)\+\zs\k\@!\S\|\>\S\|\d\+\|\u\+\ze\%(\u\l\|\d\)\|\u\l\+\|_\zs\%(\u\+\|\u\l\+\|\l\+\|\d\+\)', 'W' . l:direction )

I found that changing `\>\<` in the new version back to `\>\S` solved the issue but I have no idea what it also broke in the process.

Alternatively instead of using `cw` you can use `ce` which works as expected but for me it's a hard muscle memory to change.

**Comment by kylemacfarlane** [comment]
It was #2 that introduced this so to retain movement over . and - change `\>\<` to `\>[^\s\.\-]` instead but then you still have this bug when you try to `cw` a word before a .  or -.

I can see why #2 was added as it is nice to be able to skip over some characters but that's easymotion territory and is not what this plugin claims to do.

> Outside of "words" (e.g. in non-keyword characters like / or ;), the new motions move just like the regular motions.

**Comment by bkad** [comment]
@kylemacfarlane Thanks for tracking down the cause!

As for the motion over `.` and `-`, I will try to define the behavior of the plugin through more examples in the README so that users aren't as surprised by the behavior.

**Comment by kylemacfarlane** [comment]
@bkad You might be interested in this which I found from `:h word`:

> Special case: "cw" and "cW" are treated like "ce" and "cE" if the cursor is
> on a non-blank.  This is because "cw" is interpreted as change-word, and a
> word does not include the following white space.  {Vi: "cw" when on a blank
> followed by other blanks changes only the first blank; this is probably a
> bug, because "dw" deletes all the blanks}

I actually quite liked the motion skipping over brackets except when editing. So would it be better to revert your fix and instead add special case detection like Vim itself?

**Comment by bkad** [comment]
@kylemacfarlane Great find, I would prefer that behavior as well. I'll look into it!

**Comment by kylemacfarlane** [comment]
@bkad I tried editing JSON with this plugin last night and ran into the same problems with quotes, colons, newlines, etc as with brackets. To add them all to the regex would also prevent the motion from skipping them.

So instead what I did was undo 9591907dde8af4d8d7fbe14e99ec7d7e01791fec and added an extra mapping:

```
map <silent> w <Plug>CamelCaseMotion_w
map <silent> b <Plug>CamelCaseMotion_b
map <silent> e <Plug>CamelCaseMotion_e
map <silent> ge <Plug>CamelCaseMotion_ge
omap w e
sunmap w
sunmap b
sunmap e
sunmap ge
```

I'm not sure about all the differences between Vim's types of maps but `omap` seems to do the job.

This allows me to use `w` to move through code as expected but `cw` and `dw` are mapped to `ce` and `de`. There's still some slight differences to stock vim (e.g. `dw` doesn't delete trailing whitespace like it should) but they are otherwise a lot more predictable.
